
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassiopeiabe-deployment
  namespace: cassiopeia
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cassiopeiabe
  template:
    metadata:
      labels:
        app: cassiopeiabe
    spec:
      containers:
        - name: cassiopeiabe
          image: europe-west3-docker.pkg.dev/ag04-inventory/devcademy2023/cassiopeiabe:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "150m"

