apiVersion: v1
kind: Service
metadata:
  name: cassiopeiabe-svc
  namespace: cassiopeia
  labels:
    app: cassiopeiabe
spec:
  selector:
    app: cassiopeiabe
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cassiopeiabe-kong-svc
  namespace: default
spec:
  type: ExternalName
  externalName: cassiopeiabe-svc.cassiopeia.svc.cluster.local
  ports:
    - port: 80