apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: devcademy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              name: tcpsql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_ENABLE_HADR
              value: "0"
            - name: MSSQL_AGENT_ENABLED
              value: "1"
            - name: MSSQL_SA_PASSWORD
              value: "SQLserverDevcademy2023!"
          volumeMounts:
            - name: sql-server-data
              mountPath: "/var/opt/mssql"
      volumes:
        - name: sql-server-data
          persistentVolumeClaim:
            claimName: sql-server-pvc
