name: Build, Push and Deploy on Cassiopeia-be on GKE
on:
  push:
    branches:
      - master
env:
  DOCKER_REGISTRY: europe-west3-docker.pkg.dev/ag04-inventory/devcademy2023
  IMAGE_NAME: cassiopeiabe
  GKE_PROJECT_ID: notch-migration
  GKE_CLUSTER: devcademy-gke
  GKE_ZONE: europe-west3-c
  DEPLOYMENT_NAME: cassiopeiabe-deployment
  CONTAINER_NAME: cassiopeiabe
jobs:
  pipeline:
    name: Build, Publish & Deploy target image
    if: ${{ !contains(github.event.head_commit.message, '#skipBuild') }}
    runs-on: self-hosted
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      # Setup gcloud CLI (Inventory project)
      - name: Setup gcloud for GAR
        id: setup-gcloud-inventory
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_SA_KEY }}
      - name: Get date/time
        id: date
        run: echo "date=$(date +'%y.%-m')" >> $GITHUB_OUTPUT
      - name: Switch Connection String
        run: |-
          cd ./cassiopeia-be
          jq ".ConnectionStrings.\"cassiopeiaDB\" = \"$SECRET_CONN_STRING\"" appsettings.json > appsettings_new.json
          rm appsettings.json && mv appsettings_new.json appsettings.json
          cd ..
        env:
          SECRET_CONN_STRING: ${{ secrets.CONN_STRING }}
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Configure Docker client
        run: |-
          gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev
      - name: Push docker image to GAR
        run: |-
          docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.date.outputs.date }}.${{ github.run_number }}
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.date.outputs.date }}.${{ github.run_number }}
      # Setup gcloud CLI for GKE
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      # Deploy new version to the GKE cluster
      - name: Deploy new version
        run: |-
          kubectl set image deployment/$DEPLOYMENT_NAME -n cassiopeia $CONTAINER_NAME=$DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.date.outputs.date }}.${{ github.run_number }}
          kubectl get deployments -o wide -n cassiopeia
        shell: bash